import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LandingPage from "@/component/LandingPage";
import "../css/Bootstrap.min.css";
import '@/css/RecommendedAudios.css';
import '@/css/AudioCard.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <LandingPage>{children}</LandingPage>
        </main>
      </body>
    </html>
  );
}
